name: ChatGPT
on: [push, pull_request]
env:
  OPENSSL_CONF: /dev/null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - run: node gpt.js
    - run: sudo apt -y -qq update
    - run: sudo apt install -y bzip2 coreutils fontconfig openssl tar wget
    - run: ping -c 1 securepubads.g.doubleclick.net; wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    - run: tar xjvf phantomjs-2.1.1-linux-x86_64.tar.bz2
    - run: phantomjs-2.1.1-linux-x86_64/bin/phantomjs ai.js
    - run: wget https://securepubads.g.doubleclick.net/tag/js/gpt.js -O gpt-$(date +%Y%m%d).js;cat gpt-$(date +%Y%m%d).js | base64
    - run: test "$(sha224sum gpt.js | awk '{ print $1 }')" == "cd3e2486e093817d92ef6b297a74a4a95df9f06bd1c1f2d1e0d8b705"
    - run: set -x; test "$(sha224sum gpt-$(date +%Y%m%d).js | awk '{ print $1 }')" == "cd3e2486e093817d92ef6b297a74a4a95df9f06bd1c1f2d1e0d8b705"
